name: mocktest
on:
  push:
    branches:
      - main

jobs:
  mocktest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout Dockerfile
        uses: actions/checkout@v4
      - name: Checkout mock
        uses: actions/checkout@v4
        with:
          repository: rpm-software-management/mock
          path: mock
          fetch-depth: 0
      - name: Build new image and Load it into Docker for testing
        uses: docker/build-push-action@v6
        with:
          tags: mockenv:latest
          file: Dockerfile
          context: .
          pull: true
          push: false
          load: true
      - run: docker run --privileged --cap-add=SYS_ADMIN -t --rm mockenv:latest ${{ github.workspace }}:/mock -w /mock  sh -c "mock -h"
