name: mocktest
on:
  push:
    branches:
      - main

jobs:
  mocktest:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --privileged --cap-add=SYS_ADMIN -t --rm fedora:latest sh -c "dnf install -y mock && mock -h"
